"Traceback (most recent call last):
  File ""C:\Users\47955\workspace\super-ml-pets\V6.0\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""C:\Users\47955\workspace\super-ml-pets\V6.0\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""C:\Users\47955\workspace\super-ml-pets\V6.0\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""C:\Users\47955\workspace\super-ml-pets\V6.0\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""C:\Users\47955\workspace\super-ml-pets\V6.0\sap.py"", line 85, in step
    shp_slot = self.player.shop[action]
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""C:\Users\47955\workspace\super-ml-pets\V6.0\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""C:\Users\47955\workspace\super-ml-pets\V6.0\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""C:\Users\47955\workspace\super-ml-pets\V6.0\sap.py"", line 60, in step
    self.player.buy_food(shp_slot, tm_slot)
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\player.py"", line 16, in store_action
    targets = func(*args,**kwargs)
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\player.py"", line 213, in buy_food
    levelup = pet.eat(food)
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\pets.py"", line 126, in eat
    self._attack += food.attack
TypeError: can only concatenate str (not ""int"") to str
"
"Traceback (most recent call last):
  File ""C:\Users\47955\workspace\super-ml-pets\V6.0\sap.py"", line 85, in step
    shp_slot = self.player.shop[action]
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""C:\Users\47955\workspace\super-ml-pets\V6.0\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""C:\Users\47955\workspace\super-ml-pets\V6.0\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""C:\Users\47955\workspace\super-ml-pets\V6.0\sap.py"", line 60, in step
    self.player.buy_food(shp_slot, tm_slot)
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\player.py"", line 16, in store_action
    targets = func(*args,**kwargs)
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\player.py"", line 200, in buy_food
    raise Exception(""Attempted to buy Pet of cost {} with only {} gold""
Exception: Attempted to buy Pet of cost 3 with only 1 gold
"
"Traceback (most recent call last):
  File ""C:\Users\47955\workspace\super-ml-pets\V6.0\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""C:\Users\47955\workspace\super-ml-pets\V6.0\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""c:\users\47955\workspace\super-ml-pets\venv\src\sapai\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
