"Traceback (most recent call last):
  File ""d:\Projects\Super Auto Pets\AI\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""d:\Python\Interpreter\Python3.7\lib\site-packages\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""d:\Projects\Super Auto Pets\AI\sap.py"", line 85, in step
    shp_slot = self.player.shop[action]
  File ""d:\Python\Interpreter\Python3.7\lib\site-packages\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""d:\Projects\Super Auto Pets\AI\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""d:\Python\Interpreter\Python3.7\lib\site-packages\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""d:\Projects\Super Auto Pets\AI\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""d:\Python\Interpreter\Python3.7\lib\site-packages\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""d:\Projects\Super Auto Pets\AI\sap.py"", line 56, in step
    self.player.team.move(len(self.player.team)-1, tm_idx)
  File ""d:\Python\Interpreter\Python3.7\lib\site-packages\sapai\teams.py"", line 43, in move
    raise Exception(""Attempted move to a populated position"")
Exception: Attempted move to a populated position
"
"Traceback (most recent call last):
  File ""d:\Projects\Super Auto Pets\AI\sap.py"", line 85, in step
    shp_slot = self.player.shop[action]
  File ""d:\Python\Interpreter\Python3.7\lib\site-packages\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""d:\Projects\Super Auto Pets\AI\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""d:\Python\Interpreter\Python3.7\lib\site-packages\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""d:\Projects\Super Auto Pets\AI\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""d:\Python\Interpreter\Python3.7\lib\site-packages\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""d:\Projects\Super Auto Pets\AI\sap.py"", line 48, in step
    shp_slot = self.player.shop[shp_idx]
  File ""d:\Python\Interpreter\Python3.7\lib\site-packages\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""d:\Projects\Super Auto Pets\AI\sap.py"", line 85, in step
    shp_slot = self.player.shop[action]
  File ""d:\Python\Interpreter\Python3.7\lib\site-packages\sapai\shop.py"", line 378, in __getitem__
    return self.shop_slots[idx]
IndexError: list index out of range
"
"Traceback (most recent call last):
  File ""d:\Projects\Super Auto Pets\AI\sap.py"", line 60, in step
    self.player.buy_food(shp_slot, tm_slot)
  File ""d:\Python\Interpreter\Python3.7\lib\site-packages\sapai\player.py"", line 16, in store_action
    targets = func(*args,**kwargs)
  File ""d:\Python\Interpreter\Python3.7\lib\site-packages\sapai\player.py"", line 213, in buy_food
    levelup = pet.eat(food)
  File ""d:\Python\Interpreter\Python3.7\lib\site-packages\sapai\pets.py"", line 126, in eat
    self._attack += food.attack
TypeError: can only concatenate str (not ""int"") to str
"
